#!/usr/bin/env python
from __future__ import absolute_import, division, print_function
from openmmlib import knotAnalysis
import numpy as np
from openmmlib import polymerutils
import sys

if len(sys.argv) not in [2, 4]:
    print(
        "Usage: check fname [start end]; prints Alexander's polynomial of a polymer, or of a [start:end] subchain."
    )


try:
    data = polymerutils.load("block%s.dat" % sys.argv[1])
except:
    data = polymerutils.load(sys.argv[1])

if len(sys.argv) == 4:
    data = data[int(sys.argv[2]) : int(sys.argv[3])]
data += np.random.random(data.shape) * 0.000001
knotAnalysis.analyzeKnot(data, useOpenmm=False)
