#!/usr/bin/env python
from __future__ import absolute_import, division, print_function
import sys
import numpy as np 
import scipy.optimize
from polychrom.polymerutils import load, fetch_block
from polychrom.polymer_analyses import kabsch_msd
import os 

filename = sys.argv[1]
try:
    fol, fname = os.path.split(filename)
    data1 = fetch_block(fol, fname)
except:
    data1 = load(filename)

filename = sys.argv[2]
try:
    fol, fname = os.path.split(filename)
    data2 = fetch_block(fol, fname)
except:
    data2 = load(filename)

dataa = data1 - np.sum(data1, 0) / float(len(data1))
datab = data2 - np.sum(data2, 0) / float(len(data2))


print(
    "Shuffled distance",
    np.mean(
        [
            np.sqrt(kabsch_msd(
                dataa, datab[np.argsort(np.random.random(len(datab)))]
            ))
            for _ in range(10)
        ]
    ),
)

print("actual distance", np.sqrt(kabsch_msd(dataa, datab)))
